services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: ${PHP_CONTAINER_NAME}
    ports:
      - "${PHP_PORT_HTTP}:80"
      - "${PHP_PORT_HTTPS}:443"
    volumes:
      - ${PHP_VOLUME_PATH}
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ${POSTGRES_VOLUME_PATH}
    ports:
      - "${POSTGRES_PORT}:5432"

  adminer:
    image: adminer
    container_name: ${ADMINER_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER}
      ADMINER_DESIGN: ${ADMINER_DESIGN}
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - database
